apiVersion: v2
name: mock-ec-chart
description: Mock EC
type: application
version: 0.29.0
appVersion: 1.7.7
dependencies:
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: mock-ec-primary
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: mock-ec-secondary
