apiVersion: v2
name: mock-ec-chart
description: Mock EC
type: application
version: 0.14.0
appVersion: 1.6.15-14-PIDM-1127-refactoring
dependencies:
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: mock-ec-primary
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: mock-ec-secondary
